/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas2;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.io.InputStream;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author fajar
 */
public class register_vegenerChiper extends javax.swing.JFrame {

    /**
     * Creates new form register_vegenerChiper
     */
    private PreparedStatement ps;
    private ResultSet rs;
    
    
    public register_vegenerChiper() {
        initComponents();
        
        txt_key.setText("bdg");
        txt_key.setEditable(false);
        
        
    }

    
    // Fungsi Untuk mengecek Usernam di database
    public boolean cekUsername(String un){
        boolean cek =  false;
        Connection con = (Connection) Koneksi.getConnection();
        try {
            ps = (PreparedStatement) con.prepareStatement("SELECT * FROM 'login' where 'email'=?");
            ps.setString(1, txt_email.getText());
            
            rs = ps.executeQuery();
            if(rs.next()){
                cek = true;
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal");
        }
        return cek;
    }
    
    // Verifikasi dalam kondisi jika email dan sandi kosong
    public boolean verifikasi(){
        if(txt_email.getText().equals("") && txt_sandi.getText().equals("")){
            return false;
        } else{
            return true;
        }
    }
    
    
    // Input Data
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_sandi = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_key = new javax.swing.JTextField();
        btnRegis = new javax.swing.JButton();
        teks_pesan = new javax.swing.JLabel();
        txt_encrip_email = new javax.swing.JTextField();
        txt_encrip_sandi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Key :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Email : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        txt_sandi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_sandiKeyReleased(evt);
            }
        });
        jPanel1.add(txt_sandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 180, -1));

        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emailKeyReleased(evt);
            }
        });
        jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 180, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Sandi :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        jPanel1.add(txt_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 180, -1));

        btnRegis.setText("Registrasi");
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 180, -1));

        teks_pesan.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(teks_pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));
        jPanel1.add(txt_encrip_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 150, -1));
        jPanel1.add(txt_encrip_sandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        // TODO add your handling code here:
       
        try {
            if(txt_email.getText().equals("") || txt_sandi.getText().equals("")){
                System.out.print("Tidak Boleh Kosong");
            } else {      
                String sql = "INSERT INTO login(email, sandi)values"
                        +"('"+txt_encrip_email.getText()
                        +"','" + txt_encrip_sandi.getText() + "')";
                
                ps = (PreparedStatement) Koneksi.getConnection().prepareStatement(sql);
                ps.executeUpdate(sql);
                System.out.println("Data Berhasil Di simpan");
            }
        } catch (Exception e) {
            System.out.println("Error" + e);
        }
        
        
        
//        // membuat variable
//        String email = txt_email.getText();
//        String sandi = txt_sandi.getText();
//        String key = txt_key.getText();
//        
//        String res = "";
//        int off;
//        int j = 0, shif;
//        
//        
//        if(txt_email.getText().isEmpty()){
//            teks_pesan.setText("Harap isi email anda !!");
//        } else {
//            // Vegenere Chiper bagian Email
//            for(int i = 0; i < email.length(); i++){
//                shif = ((int) key.charAt(j)) - 97;
//                j++;
//                j%= key.length();
//                off = ((int) email.charAt(i) + shif) % 256;
//                res += (char) (off);
//            }
//            System.out.println("Vegenar Chiper Email : "+res);
//            
//            // Vegenere Chiper Bagian Sandi
//            String res1 = "";
//            for(int i = 0; i < sandi.length(); i++){
//                shif = ((int) key.charAt(j)) - 97;
//                j++;
//                j%= key.length();
//                off = ((int) email.charAt(i) + shif) % 256;
//                res1 += (char) (off);
//            }
//            System.out.println("Vegenare Chiper Sandi : " + res1);
//        }
        
        
        
        
    }//GEN-LAST:event_btnRegisActionPerformed

    private void txt_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyReleased
        // TODO add your handling code here:
        
        // membuat variable
                String email = txt_email.getText();
                String sandi = txt_sandi.getText();
                String key = txt_key.getText();
        
                String res = "";
                int off;
                int j = 0, shif;
        
//                email = email.toUpperCase();
//                for (int i = 0; i < email.length(); i++) {
//                    char c = email.charAt(i);
//                    if (c < 'A' || c > 'Z') continue;
//                     res += (char)((c + key.charAt(j) - 2 * 'A') % 26 + 'A');
//                        j = ++j % key.length();
//                }
//                return res;
//                   txt_encrip_email.setText(res);
        
                if(txt_email.getText().isEmpty()){
                    teks_pesan.setText("Harap isi email anda !!");
                } else {
                    // Vegenere Chiper bagian Email
                    for(int i = 0; i < email.length(); i++){
                        shif = ((int) key.charAt(j)) - 97;
                        j++;
                        j%= key.length();
                        off = ((int) email.charAt(i) + shif) % 256;
                        res += (char) (off);
                    }
                    System.out.println("Vegenar Chiper Email : "+res);
                    txt_encrip_email.setText(res);
            
                }
        
        
    }//GEN-LAST:event_txt_emailKeyReleased

    private void txt_sandiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sandiKeyReleased
        // TODO add your handling code here:
        
                String email = txt_email.getText();
                String sandi = txt_sandi.getText();
                String key = txt_key.getText();
                
                
//                String res = "";
                int off;
                int j = 0, shif;
                String res1 = "";
                    for(int i = 0; i < sandi.length(); i++){
                        shif = ((int) key.charAt(j)) - 97;
                        j++;
                        j%= key.length();
                        off = ((int) email.charAt(i) + shif) % 256;
                        res1 += (char) (off);
                    }
                        System.out.println("Vegenare Chiper Sandi : " + res1);
                        txt_encrip_sandi.setText(res1);
        
    }//GEN-LAST:event_txt_sandiKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register_vegenerChiper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register_vegenerChiper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register_vegenerChiper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register_vegenerChiper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register_vegenerChiper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel teks_pesan;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_encrip_email;
    private javax.swing.JTextField txt_encrip_sandi;
    private javax.swing.JTextField txt_key;
    private javax.swing.JTextField txt_sandi;
    // End of variables declaration//GEN-END:variables
}
